### ISSUE TITLE
the project structure does not conform to the standard library structure

### ISSUE THREAD

**Issue by sk-ip** [Quansight-Labs/udiff#1]
The project directory structure does not look good, compared to the standard library structure. 
for making packages for PyPI the directory structure should be something like this
```
project-root
├──src/
   └──package_name/
      └──__init__.py
├──tests/
   └──package_name/
├──.coveragerc
├──.gitignore
├──LICENSE
├──README.md
├──setup.cfg
└──setup.py
```

**Comment by sk-ip** [comment]
@hameerabbasi , I would like to work on this if the above directory structure is fine to go with.

**Comment by hameerabbasi** [comment]
Go for it!
