### ISSUE TITLE
a problem in np.power

### ISSUE THREAD

**Issue by sangyx** [Quansight-Labs/udiff#8]
Hi, I meet a problem when calculating the derivative of the function like:

![image](https://user-images.githubusercontent.com/32364921/75126528-528a6800-56f5-11ea-9e0a-ddb9b7087910.png)

The code to calculate it is:
```python
lambda x: np.sin(np.power(x, 2)) / np.power(np.sin(x), 2)
```

If we set x = -0.3, it's no problem because the value is in the domain of the function. But because the code of `np.power` should calculate the log of x. I can't get the correct diff of y.

```python
def pow_diff(x1, x2):
    ftog = x1[0] ** x2[0]
    gplogf = np.log(x1[0]) * x2[1]
    gfpof = x1[1] / x1[0] * x2[0]
    return ftog * (gplogf + gfpof)
```

**Comment by hameerabbasi** [comment]
This now works if instead of `-0.3` you pass in `complex(-0.3, 0)`.

**Comment by hameerabbasi** [comment]
The reason is simple, it passes through complex numbers and so you need a complex dtype to handle that. Alternatively, instead of using `np.power(x, 2)` you can use `x * x`.

**Comment by hameerabbasi** [comment]
For context, the reason this is so complex is because of this: https://en.wikipedia.org/wiki/Differentiation_rules#Generalized_power_rule

**Comment by sangyx** [comment]
Thanks. I understand it. We need to consider `np.power` as a power exponent function instead of a power function.
